export const urlCache = [
    '/',
    '/manifest.json',
    '/service-worker.js',
	'/index.html',
	'/pages/nav.html',
	'/pages/home/home.html',
	'/pages/home/home.css',
	'/pages/kisah/kisah.html',
	'/pages/kisah/kisah.css',
	'/pages/dalil/dalil.html',
	'/pages/dalil/dalil.css',
	'/pages/fakta/fakta.html',
	'/pages/fakta/fakta.css',
	'/pages/pesan/pesan.html',
	'/pages/pesan/pesan.css',
	'/pages/referensi/referensi.html',
	'/pages/referensi/referensi.css',
	'/js/materialize.min.js',
	'/css/materialize.min.css',
	'/js/authServiceWorker.js',
	'/css/style.css',
    '/js/script.js',
    
    /** image assets */
    'assets/illustration/ark3.jpg',
    'assets/illustration/ark4.jpg',
    'assets/illustration/books.jpg',
    'assets/illustration/noah ark.jpg',
    'assets/illustration/statue.jpg',
    'assets/icon/book.png',
    'assets/icon/compass.png',
    'assets/icon/home.png',
    'assets/icon/icon.png',
    'assets/icon/icon-192.png',
    'assets/icon/logo.png',
    'assets/icon/memory.png',
    'assets/icon/morality.png',
    'assets/icon/research.png',
    'assets/icon/scroll.png',
    'assets/icon/up.png',
    'assets/gif/drown.gif',
    'assets/gif/sail.gif',

];